# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8da086194a9233497a288098c4dda0dc17df5cddfe645dbfe80516f11ccff1157579919509bd206aa757c1e4f20fce66c2cf8ba5d547d9104035c040e44650a

test:
  secret_key_base: d01375e35de5fd3eb68daeff65c254eee68f73367ad603f91af85b369899c092a568114a270acaba27437c6562413415dd712262227e115c5b64865091709515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
